// Lightweight reference content; no scene snapshots, images or tutorial assets.
export const guideTopics = [
  { id: 'import-head', title: 'Import your own head', category: 'Getting Started', keywords: 'character body obj reference import mesh', context: 'Start the guided workflow to import and fit a head or full-body OBJ.', description: 'Use your own character as the reference for a hairstyle. Importing replaces the current head/body reference. The interactive guide spotlights each control inside the app.', steps: ['Choose File, then Import Head Mesh or Import Full Body Mesh.', 'Choose your OBJ file.', 'After import, fit the head and scalp guide in Main.'] },
  { id: 'draw', title: 'Draw a strand', category: 'Strands', keywords: 'create hair pencil curve', context: 'Use the Strands workspace.', description: 'Draw a root-to-tip curve to create a strand on the live surface.', steps: ['Choose the live surface, then activate Draw Strand.', 'Draw from the root toward the tip in the viewport.', 'Select the strand to adjust its shape and topology.'] },
  { id: 'shape', title: 'Width and depth curves', category: 'Strands', keywords: 'taper profile thickness shape', context: 'Select a strand in the Strands workspace.', description: 'Width controls the sideways silhouette; depth controls front-to-back thickness. Their curves vary these dimensions along the strand.', steps: ['Select a strand and expand Strand Shape.', 'Adjust Width or Depth for the overall size.', 'Open the width or depth curve editor to shape the profile from root to tip.'] },
  { id: 'topology', title: 'Strand topology', category: 'Strands', keywords: 'loops radial along curve resolution polygons', context: 'Select a supported strand in the Strands workspace.', description: 'Topology controls the mesh resolution around and along a strand.', steps: ['Select a strand and open Topology.', 'Radial adds resolution around the profile; Along Curve adds loops along its length.', 'Use enough loops for the silhouette and bends without unnecessary density.'] },
  { id: 'mirror', title: 'Mirror strands', category: 'Strands', keywords: 'symmetry linked left right', context: 'Use the Strands workspace.', description: 'X mirroring helps create a symmetrical hairstyle. Linked mirror partners can share edits.', steps: ['Use the X mirror control for mirrored editing.', 'Use the selected strand’s radial menu for mirror and decouple actions.', 'Decouple a linked pair when the two sides need independent changes.'] },
  { id: 'move-brush', title: 'Move Brush', category: 'Brushes', keywords: 'sculpt grab drag soft falloff', context: 'Use the Strands workspace.', description: 'Move nearby strand points together using a soft brush influence.', steps: ['Activate Move Brush and set its radius and strength.', 'Drag in the viewport to reshape nearby strands.', 'Select strands first to restrict sculpting to that selection.'] },
  { id: 'smooth-brush', title: 'Smooth Brush', category: 'Brushes', keywords: 'sculpt relax soften', context: 'Use the Strands workspace.', description: 'Smooth nearby strand points to soften irregular bends.', steps: ['Activate Smooth Brush.', 'Adjust radius and strength, then brush over uneven curves.', 'Use Preserve Tips when the strand endpoints should stay in place.'] },
  { id: 'inflate-brush', title: 'Inflate Brush', category: 'Brushes', keywords: 'sculpt thickness volume width depth', context: 'Use the Strands workspace.', description: 'Inflate changes strand width and depth profiles with a soft brush.', steps: ['Activate Inflate Brush.', 'Choose the profile to affect in the tool settings.', 'Brush over the strand to adjust its volume locally.'] },
  { id: 'live-surface', title: 'Live surface', category: 'Navigation', keywords: 'head scalp draw placement snapping', context: 'Use a drawing tool that exposes Live Surface.', description: 'The live surface is the surface used to place newly drawn strands.', steps: ['Choose the desired surface in Live Surface.', 'Draw the strand against that surface.', 'Changing this choice controls placement; it does not replace existing strand geometry.'] },
  { id: 'binding', title: 'Binding blend', category: 'Rigging', keywords: 'skin weights smooth deformation bones', context: 'Use Rigging and select a bound chain or its strands.', description: 'Binding connects strands to bones. Binding Blend softens transitions between joint influences.', steps: ['Create and bind a chain for the source strands.', 'Select the chain and expand Binding.', 'Increase Binding Blend for softer transitions, then test the result in Pose Preview.'] },
  { id: 'physics', title: 'Physics preview', category: 'Rigging', keywords: 'simulation gravity stiffness damping play stop', context: 'Use the Rigging workspace with bound bone chains.', description: 'Preview temporary bone motion using gravity, stiffness and damping.', steps: ['Press Play in Physics Preview.', 'Select the head handle and move or rotate it to test motion.', 'Stop restores the starting pose. The simulation itself is not saved or exported.'] },
  { id: 'limits', title: 'Bone rotation limits', category: 'Rigging', keywords: 'constraints cone sideways forward locked', context: 'Use Rigging and select an individual bone.', description: 'Rotation limits restrict simulated bone movement with an editable cone.', steps: ['Select a bone and expand Rotation Limits.', 'Choose Free, Limited or Locked movement.', 'Adjust sideways and forward/back angles; Rotate Cone offsets the constraint in local space.'] },
  { id: 'materials', title: 'Assign a material', category: 'Materials', keywords: 'color colour shading appearance', context: 'Select a strand or editable mesh.', description: 'Materials control appearance and can be shared by multiple objects.', steps: ['Select an object and expand Selected Strand or Selected Mesh.', 'Choose its Material or use + to create one.', 'Use the Materials tab to edit the material. Shared material changes affect all its users.'] },
];

export function searchGuideTopics(query = '', category = '') {
  const words = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  return guideTopics.filter(topic => (!category || topic.category === category)
    && words.every(word => `${topic.title} ${topic.category} ${topic.keywords} ${topic.description}`.toLowerCase().includes(word)));
}
